import { Inter } from 'next/font/google'
import './globals.css'
import { GeistSans } from 'geist/font/sans'

export const metadata = {
  title: 'jammmer',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className}bg-gray-50`}>{children}</body>
    </html>
  )
}
